#include<iostream>
using namespace std;
string ANNIVERSARY13TH()//今天是初音未来13周年纪念日，初音生日快乐！！！ 
{
	int NUMBER39;
	string HATSUNE="",MIKUMIKU;
	char ONION;
	while(cin>>ONION)
	{
		if (ONION=='[')
		{
			cin>>NUMBER39;
			MIKUMIKU=ANNIVERSARY13TH();
			while (NUMBER39--) HATSUNE+=MIKUMIKU;
		}
		else 
		{
			if (ONION==']') return HATSUNE;
		    else HATSUNE+=ONION;
		}
	}
}
int main()
{
	cout<<ANNIVERSARY13TH();
}
//.                        .oO@@@O^.    .\@@@@@@OOOOOOo`*****\OOO@@OOOOOOO@@@@@@@@O.             .,OOOO..            .OO@OOO^.           .=OO^..              ..O@@OOOOOO\`.,\OOOOOOOOOOoo`. .[OOo`..                             .         .,`..
//\`.                      .OOO@@@O`       ,O@OOOOOo^***..]OOOO@@@O^ .[[[`\O@@OO@@@\.             .=OO@^.            .OO@OOO^            .=O/..               ./@@OOoo`.   .[O\`*[OOOO@@OOOOOOOOOO].                                    .,o/.....
//.,\.                     =O=O@@@@O.     .,OOO/[******=OOO@@@@@@/`        =@@OOO@@@`.             .=@@\.          .,]OO@OOO.            .oo`.               ./@@@Ooo`.        .[OO],\OO@@@@OOOO]...\`.                              .]O[. ...   
// ..,\. ..]]]]..          =O.\O@@@@\]].  .OOO`,^/]]/OOO@@@@@@[.            ,@@OOOO@O.              .,@@]]]@@@@@@^,@OOOO@@OO*..[[\]].    .OO.               .=@@@Ooo^.             .[OO][OO@@@O[[\O\..[\.                        .,/O`.  ...     
//   ..,O/.,]O@@\]/[OO]].  =O.*OOOOOooO@@\.,O@OoooOOOO@@@@@@\.               .O@OOOO@^.      ... ,]@@@@@@@OOOOOO@@@@OOO@@@@@@@@@@O\]`..,[[@^.               .O@@Oo\/.                  .OOooOO@@O].,\\..,\.                   .]OO`.  ....       
//    ...\@@@@@@@@@OOOOOOOOOO..,OOOOOOOO/O@@@@@@OOOO@@@@@@@@Oo.               .\@OOO@@.     ./^.=@@@OOOOOoooo[\oO@@@@OOOO@@@@@@@@@@@@@@@@@\]]..[[]`        .=@@Oo^/.                  ,OO@OOOOOO@@@O`......`.              ./OO/.   ...          
//      ..,O@@OOOOOOOOOOOOOOOoOOOOOOOO/*..=O@@@O[O@@@/[\@@@@@@O`.              .=@@O@@\]/OO@@@.,/@@OOooooooOOO@@@@/[O@OOO@@@@@OOOOO@@@@@@@@@@@@@@\]`.,\]`  ,@@@O^/.                 ./O@@Oo` .[OOOO@@O`......,*.       ../OO/.   ....            
//        ..,O..[[OOOOOOOOOOOOOOOOOO/*....,oOO^         .O@@@@@@\.              .=@@@@@@@@@O@@@@@@@OOooOOO@@OOO@@`    .@@@,^     [[O@OOOOOO@@@@@/\@@OO\`. ,OO@O`=.                 .O@@OO^.     .\OOOOOO`. .  .\.   .,/OOO`.   ...               
//          ..,\      ,\OOOOOOOOOOo****]/OOO@@O.          .\@@@@@\.          .,/\@@@@@@OooOO@@@@@@@@@@@@@/[.           @@@=.             [[OOOOOO@@@@@@@OoOO@@.=\      ,/@@@@@@@@@/O@@O\`          ,OOoOOO\......oOOOOO[.   ...                  
//           ...\`       .[\O\ooo`***/oOO@@@O`              .\@@@@\.       ,/O@@@@@@@O/=*[OO@@@@   [[                  O@@=                     [\OOoOO@@@@@@\/\..,O`.OO      .[[@OOOoO\`            .\OoOOOOO],OOOO/.   ...                     
//             ...\`      .=O=Oo/**ooOOO@@@`                  .,@@@^.    .@@@@@@OOOOo^`*/OOOO@@/                       =@^/                          [\OoOO@@@@@@OO\`.[@        /OO^/[@@@@@@].         .[OOO@@OOOO[.  .*..                       
//               ...\`   .]OOOOoOOOOOO@@@@@OO\.    .   ..]]]]]]. ,@@^./\. .@@OOOoo\]ooOOOO@/[@@                        =@^^                             .O@OOO@@@@@@OO]` [\.   /O`,..]]]/@@@@@@@`       .,@OOO@@OOO]/Oo.                         
//                 ..,O`   =OOOOOOOO@@@@@@@@@OOO]]@@@@@@@@@@@@@@@@@@`./O@@@@@OOOoOOOOO@@@@.  =@^      ]]]OOOOOOOOOOOOOO@@oOOOOooooooooooOOOO]].         /..,` [@OO@@@@/[o\] [\///O@@@@@@@@@@@@@@@@@\. ,/OO@@@OOO@OO`...,`.                       
//                   ..,O/@@@@@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@/ ]OOOOO@@@@@OOOO@/` ,OOO^   @@@OOO@@@@@@@@@@@@@@@@@@@@@=@@@@@@@@@@@@@@@@@OOO]`*,[\]  ,^.,`     ,\@O@@@@`,\\./\@@@@@@@@@@@@@@@@@@@@@OO@@@Oo/\OOOOOO^....\.                      
//                   .*..,@@@@@O.   .\@@@@@@@@@@@@O@@@@@@@@@@@@`,/OOOO/\OO@/\@@@[      ,OOO/OO@@O@@@@@@@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@OOO\`*O.,`          [@OO@@@],\\.,\@@@@@@@@@@@@@@@@O@@@@Oo*,/`..\OOOO\.. .\.               .*`.  
//    ....      ...........,O@@@^. .]@@@@@@@@@@@@@@@O@@@@@@@@`,OOOOo`,]/@O@\@@@^       ]@O@@@@@@@OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@/,//O`         =@@@OO@@@\[o] [@@@@@@@@@@@O@@@@O/`]@@@@@\..,OOOOO.  .=`         .,`[..     
//   ................... ....=@@.,@@@@@@@@@@@@@@@@@@@@O@@@@@@OOOOooOO@@@@ ,@@@@     ,O@@@@@@@@@@@@OOO@@@@@@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@,@@@OooO`       \@@@@@OO@@@`\\.,@@@@@@@@@@@O`.]@@@@@@@@@@@\.\OOO\.  .,^.   .]/[....       
//             ..............,.\@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOOOO@@@@@.@@@@`  ,/@@@@@@@@@@@@@@@@@OOOO@@@@@@@@@@@@@@@@@@@@@@OOOO@@@@@@@@@@@@@@@@@@@@\@@@@@@@@oO\      @@@@@@@@O@@@`,o`.\@@@@@[.,/@@@OOO@@@@@@@@@@@OO/o*.   ,\/O[. ...          
//                ...........=\..\@@@@@@@@@@@@@@@@@@@@[@@@@@@@@@@@@@@@@@@@@@@` ]O@@@@@@@@@@@@@@@@@@@@@@OOOOOO@@@@@@@@@@@@@@OOOO@@@@@OOOOO@@@@@@@@@@@@@@@@@@@@@@@@OoO`   ,@@@@@@@@@@O@@OO@@@O[.,@@@@@@@@@@@@@@OOOO@@@@@O/,`...[`. ...             
//               .........*..**`..,@@@@@@@@@@@@@@@@@`/OOOO@@@@@@@@@@@@@@@@@@`/O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOOOOOOO@@@@@OOOOOOOOOOO@@OOOOOOOO@@@@@@@@@@@@@@@@@@@@O`\`  ,@@@@@@@@@@@@@@@^ ]/\@@@@@@@@@@@@@@@@@@@@OOOO@@``*...]/^.               
//               ........*,^.^****o.,O@@@@@@@@@@@@\OOOO\O@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@OOOOOOOOOOOOO@@OOOOOOOOOO@@@@@@@@@@@@@@@@@O`\` =@OO@@OO@@@\@@O@@O[o.\@@@@@@@@@@@@@@@@@@@@@OOOO^*.....,^.              
//             .,/\]**...=o^*Oo^**/O\`=/@@@@@@@@O/OOO`,@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@@@@OOOOOOOOOOOOO@@OOOOOOO@@@OO@@@@@@@@@@@@@@@@`\`=@OOO@@/./@@@@@O@@O\.,@@@@@@@@@@@@@@@@OOOOO` ,@^*..*..=`              
//..        .*.*****ooooooo^*Oo^**Oooo\`\O@@@@@OOOOO/@@O@@@@@@@@OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@@@@@@OOOOOOOOOOOOOO@OOOOOOOO@@@@@O@@@@@@@@@@@@@@O`\=@@/]@@@@@@OOO@@O@@^..,@OO@@@@@OO@OO@@O[ ]@@@@@^*O\*  \.             
//.........**....**oooooooo^*OO^**Oooo\o^.\@@@@@OO@@@O@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@@@@O@@@OOOOOOOOOOOOOOOO@OOOOO@OO@@@@@OO@@@@@@@@@@@@@O@@OO\OOOOOOOOOOOO@O@O`*.\OOOOO@@O@@[.]O@OO@@@@@@`OO`  .\.            
//....................=oooo^*OO^**ooooo//\\.\@@@@@@@@@@OOOOOO@@@@@@@@@@@@\[O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOO@@@@@@@@O@@@@OOOOOOOOOOOOOOOOOOOOOOOO@@@@@@@@O@@@@@@@@@@@OO\OOOOOOOOOOOOoooOO@`OO^=/OoOO/` ]O@@@OOOOOOOO@@@oO^   =`            
//...................*ooooo^*Oo^**oooo\\*^,/\.\@@@@@@OOOOOOo[[`,[O@@@@@@@@@@@]**[[@@@@@@@@@@@@@@@@@@@@@@@@OOOOO@@@@@@@@@@OOO@@@OOOOOOOOOOOOOOOOOOOOOOOOOOO@@@@@@@OO@@@@@@@OOOO\,OOOo[**.....*,\oO@/O@O\@]OOOOOOOOO@@@OOOOOOO@O\*... O].          
//............... ...*[/ooo^*Oo^**ooo`,=`=^*.\^ \@@OOOOo[]o/[[\O/OOO@@@@@@@@@@@@@@]********,[ooooooooOOOOO@@@@@@@@@@@@@@@OOO@@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@@@@@OO@@@OOOOOOO\*O/............=ooOO@@@O,OoOoOOOOOOOO@@@OOOOO@`,O*..=@@\..]]/[[]]
//..      ...........*...[o^*oo^**o***]`//..**.,..Ooo[.         ,oO@@@@@@@@@@@@@@@@@@@@@@\]]]ooooOOO@@@@@@@@@@@@@@@@@@@@OOO@@@@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@@@@OOOO@OOOOOoo\.`          ..*.*=\O@@@@`OoooOOOOOOOOOO@@@OOO@\O^.]/[`.,]/[.   .
//      ............***.....*/[***/**=*]^..*/**...             ,\OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@O@@@OOOOOOOOOOOOOOOOOOOOO@OOOOOOOOOOOOO@O@OOOOO@OOOooo`*..             .**[o@@@@\\oooOOOOOOOOOOO@@@@@^OO`OO[`.........]
//    ..............*.......^..`**^*=o^*****....   .        .]]OOOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@O@@@OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOOOoooo***..              .**\\@@@\=OoooOOOO@@OOOO@OOOOOO^O.....,]OO^.  
//  ..............*********.`^..**oo.,**,/*..........` ,/o/OOOOOOOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@O@@@OooooooooOOOooooooOoOOOOOOOOOOOOOOOOOOOOOOOOoOOOoo^***...                **=@@@@\@@@OO@@@@@[. ...[@OOO.[[OOOOOOOOO` 
///]. ................*...*.*`*.**o],oo]`..[]   ...*..,. \OOOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@@@@@OooooooooooOOoooooooooooOOOOoOOOOOOOOOOOOOOOOOoOOOoo****...              ]O[*]@@@@@@@@@[,]`[..]]O@O@OOO`. OOOOOOOOOoO
//@@@@@\` ......................^*/\/[/ooooo]..,,.*.*..... [@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@@@@@@O,[[\ooo/ooOOooooooooooooOOOOoooOOOOOOOOOOOOOOOoooOOo^*****..        ,//`,/@@@@@@@@@@@O]/OOOOOOOOOOOOOOOo^ OOOOOOOOO@O
//@@@@@@@@O]   .................oo^..*[\oooooOO/.***,]   =o..@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\@@@@@@@`**********,OO``****,ooooooOOOOoooooOOOOooooOOOOOoooOOoo******    ]@\*,O@@@@@@@@@@/\OO=/[[oooooOOOOOOO@OOOo =OOOOOOOOO@
//@@@@@@@@@OO`o]  ..............oo^....  .,ooO^***,o].*oo\.\O`,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@@@@@@@/************=O^**********,*/OOOOoooooooOOO^.ooOOOOOoooOOo\]^***. =\,O@@@@@@@@@@[.   *OO\O===ooooooOOOOO@OOoo =@OOOOOOOOO
//@@@@@@@@OO`*\O@@@]   .........oo^..        ..***..]oooooO\*=O.\@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`............*OO************,^OOOO/oooooooOOOooooOOOOOoooOOoooo^*,  =@@Oo[`@@[         ,OO/\`=/oooooOOOOO@OOo` =O@@OOOOOOO
//@@@@@@@@OO**oO@@@@@@@`   .....\o^.          **`.*oooooOOOOo*.=\.\@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@O^............../@^........*.**=*OOOO^**/=ooooOOOoooOOOOOooOOOOoo/^o*^  =O...,\            .OO\./*/\oooOOOOO@OO^. OOO@@OOOOOO
//@@@@@@@@@O[*oO@@@@@@@@@O\`   .[*^           **./oo/ooo`\O`***..\\,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO/...............,@@/............*O*@OOO^**..**[o\oOOoooOOOO\=OoOOOoooo^\    [@@OOO`            @O\ ,`\ooooOOOO@OO*. @OOO@@OOOOO
//@@@@@@@@@@`\\/@@@@@@@@@O@@^.,`**.          ..]`,/`/`   o*..,/OOOoO^,@@@@@@@@@@@@OOO@@@@@@@@@@@@@@@@@@@@@@@@OO/`...............,OOO/............./O=@OoO^..******`^oOOooOOOOO,oOOOOooooo=.     =@@Oo\            @\\  \/\oooOOO@Oo. .@OOOOO@OOOO
//..,@@@@@@@@@O@@@@@@@@@@@@@O@@O/*`   ........**=``     ...]oOOOOOoOO@`\@@@@@@@@@@@@@@@@@OOOOOOOOOOOOOOOOOOO,......     .  .../@OOO`...  ......../@^OO@oO^...*******,\OO/oOOO@^oOOOOOooooo`       @@@`O*...[,`    ]@@@@@@@@@OOO@Oo^. =@OOOOOO@OOO
//`...\@@@@@@@@@@@@@OOOo@@@@@@@O,`@@OO]  ....***.       .,o*ooOOOOOOOOOO.\@@@@@@@@@@@@@@@@@@@@@@OOOOOOO[,,. .             ,/OOOOOO`............,OO//OOOOO`......******OOooOOO@^==OOOOoooo/^        =@*,O`.......`.[\OOOOOO\[[[[OOo`./o\/[O\OO@@OO
//@O`..O@@@@@=@@@/O@OOOO^  [@@@@o^@@@@@@OO`  .**       .,,*=oooOOOOOOOOOO\,@@@@@@@@@@@@@@@@@OOOO@@/`],.              .]OOOOOOOOO`        ...../OO^/OOOOOO..........***=OooOoO@^*=OOOOOooo^^        =\\@\\`      ...[/OO` ,[\\]]@Oo..^            
//@@@O`*OO@@@=@O*.=@OO@`   ,@@OO**OOOOOO@OO@@\.         .*.=ooOOOOOOOOOOO/O\=@@@@@@@@@@O@OOOO@O`**.            .]/OOOOOOOOOOOO`.           ,OOO//OOOoOOOO....^........*Oooooo@^`=OOOOOooo*^        ^.=@@^O.        ...\^    \OO@O^. =OOOOOOOOOO@@
//@@@@@O=\O@@^OO*.=@@@. ,/@@@OOO**OOOOOO//@@@@@@^       ..**=oOOOOOOoooooo\=O`\@@@@@OOOOOO@@[,..       .....       .[[\OOOO[            ,/OO/,/OOOOooOOO^...=^.........=Ooooo@`*,OOOoOoo/*^        ^.=@@^.^            ..\`  =@O/.. @OOOOOOOOOOO@
//@@@@OO^*OO@@,O*^=@@./@@@@@@@@O**OO@@@@@@@@@@@@^...    ..**]oOOoooooooooOOo`=O`\OOOOOOO@O`.      .]OOOOOOOOOOOOOOOOO@O\].            ,`.]OOOOOOOooooOOO^...^`.........=@Oooo@**=OoOoOoo**^        ^./@@@@@^              ..\]@o`. =OOOOOOOOOOOOO
//@@@OO^**OOOO\=oo`\@@@@@@@@@@@O]`@@@@@@@@@@@@@@^    .. \` .,\o*o\oooooOOOoooO*\\,OOOOO/*`    ]OOOOOOOOOOOOOOOOOOO[`***********,]]/OOOOOOOOOOOoooooooOOO...*,..........=OOOoO/.*OOoOoOo`**^        \.@@@@@O/     ....        =O^...@OOOOOOOOOO@@@
//@OO/****@@@@@@@O\oo@@@@@@@@@@@oo@@@@@@@@@@@@@@       .\/\@@]..,/\ooOOOOoooO/o`*\\,OO`*  ,OOOOOOOOOOOOOOOOOO[*.      .]]OOOOOOOOOOOOOOOOOooooooooooOOO^  .=^..........O=OO\O^.=OooOoOO***^        ==@@@OOO^   ........*..  .Oo.. /OOOOOOOOOOOO@@
//Oo`*****@@@@@@@@@O@@@@@@@@@@@O[[OOOOO@@@@@@@@@       =\O@@O`\OO].[OOOOooO/oo\\\`,o`.../OOoOOOOOOOOOOOOOO`.  ]/OOOOOOOOOOOOOOOOOOOOOoooooooooooooooOO/  .*O`  .......=^/oo@O..OooOO/oO***.        .@@@@OOO`. ........****,`/o*. =^...[OOOOOOOO@@
//oooo[`**@@@@@@@@@@@O@@OOO@@@@@o^@@@@@@@@@@@@@\]]]]]]]/\O@@@OOO\O@@@\/\[\o[[\oo,[o\...\ooOOOOOOOOOOOOo`.,/OooooOOOOOOOOOOOOOOOooooooooooooooooooooOO/  .*O/      ...,/*O/oO^./o^oOOo=O**..  ..,]]]]@@@OOo\OOooooOO\`.*****=\^..,^.       .[O@@@@
//********@@@@@@@\\OOO@@@@@@@@@@o\@@@@@@@@@@@@@@@OOOOOOOO@@@OOO@@@@@@@@@\].,\`***,/.,\``*oOOOOOOOOooO`,/ooooooOOOOOOOOOOOooooooooooooooooooooooooooO/  .,OO.        ,`*O\/\O.=Oo,oO\^*O*.*  . ..*ooOO@Oo[..=`.......*,,[O\]/*...@O`...           
//********@@@[\/@@@OOoO@@@@@@@@@oo@@@@@@OoO@@@@@OOOOOOOOO@@OOO@@@@@@@@@@@Ooo\..,***...,\/\oOOOoooooO/ooooooooOOOOOOo\oooooooooooooooooooooooooooooO^ ../OO`        /*/O@[\O.,@o*=o/=o*O*..  . ../ooOOOo*...,   .`...... ..O*..,@OOOOO]......     
//oo**]/`*]@@@@@@@@OOOOO@@@@@@@@oO@@@@@@@@@@@@@@,OO@@@@@@@@OO@@@@@@@@@@@@@@OOO`*........,oo*=ooooooo/ooooooOOOOooo=o,ooooooooooooooooooooooooooo=O`../OOO`       .*/OOOO,/`,OO^,oO`=^*O*.]/..]]]/],OOOO/`*`...  .*.[]. ..O*.,/...[@@OOOOO]`......
//oo/*****O@@@@@@@@@OOOOO@@@@@@@OO@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@O@@OOOo\`*.......****[oooooooooooOo/o************************[[[[\o[\/o`.,OOOOO.     .]OOOOOOOOO`,OoO//O/*=^*o,OOOOOOOooOoooOoo,.*....  .^...*.O...\..    ..,\@OOOOOOOOO
//`*******O@@@@@@@@@@@@O@@@@@@@@OO@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@OOOOOOOOO@@@\]`....****,ooooooooooo`********************************]`./O\``o`  ,]]OOOOOo\oOOO@`=Oo/OOoO***^,o@OOOOOOOoOO^oOOoo*.`.....   \*../...,@@O].       ..[@OOOOO
//*****]/o@@O@@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@=@@@@@@@@@@@@@@@@@@@@@@@@OOOOOOOOoooooOO@@@O][[o]]]o\o[\o^/`,`****************************,/\/O[[[[o/]/OOOOO[`*=oo[/OO/./OOo^OoO***=oo@@OOOOOOOOOO*oOOOo^=O\......  ,]/.. /OOOOOOOO@O]`      .[@O
//*ooooooo@@O/,*.[\@@@@@OO^,@@@@@@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@OOOOOOOoooooooooo/\/[[OOOOO@@@OO@@O\]********************]]/[[`*[`,]]]ooOoOO\Ooo`***=*=oo/oO`]OoOOO\OO/,***o/@@OOOOOOOOO^=oOOoooooOO`.....  /...O.,OOOOOOOOOOOOOO@O]`   
//***]`,ooO@@O=\*]*. .[O@O\^=O@@@O@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@OOOOoooooOOOOoooo/[[`****..***,o/**********************.******....../O/\`*ooo\]]]***][,]o`/OOoOOOOO/Oo^^*=O@@@OOOOOOOOO*OOOO*oooOOOO\....,^..,O`..=OOOOOOOOOOO/.... ..,
//*,[[oOOOOOOO\,O`***.    .[\OO@OO@@@@@@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@@@@OOOOoOooOOO@@@@OO\]*,[O\`***********************...................,]/[...*]]]]]]`,,]\OOO\\OOOOOOO/\OOooo=@@@@@@OOOOOO^=OOOoooooOOOOOO`.=`. /`  \``=OOOOOOO/.... ,//[[[
//**...,`],[OO@\,@O**`**.      ,/[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@OoOoO@@@@@@@@@@@@@@@@@\`*\o`***************......................]`...]@@@@@@@@@@@@@@O\/ooOOOOOOOoooOOoooO@@@@@@@OOOOO.OOOOooooOo^OOOOOO*.,/...   ,\[OOOOOOOO/         
//******.....[],\.O@\*`*`*,]OOOO**O@@@@OO@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@@O@OOOO@@@@@@@@@@@@@@@@@@@@@\**`************.........................,/@@@@@@@@@@@@@@@@@@@OOoOOOOOOOoooOOooO@@@@@@O@OOOO/=OOOOooooOo`OOOO/*./`.......   [oOO[.            
//**********]/` \@OOOOOOOO@@O@@O**O@@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOO@@@@@OOO@OOOO@@@@@`.[@@@O`.``********......................../OO@@@@OO@@@^  =@OO@@@@@OOOOOOOOOoooOOoO@@@@@@@@@@@OO,OOOOooooooo,OO/`.,OOO`.....,\`.   ,`             
//...**=oo=OOOO\.,OO@O[OOOO@@@O`*,OO@@@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OooOOOOO@@@OOO\  =O@OO^.*******........................,OOOOO[*,O@@OOOO]OOOoOO@@@@@OoOOOOOoooOOO@@@@@@O@@@@@o^OOOOOOoooOo/=/^../OOOOOO`......\O^     ,,.        
//....***,OOOOO@@\.\@OOoOO@@@OoO]^O@@@@@OO@@@@@@@@@@O@@@@@@@@@@@@@@@@@@@@O@O@@@OOooOOOOO@@@O@@@OOOOOoOO\[*****.........................*=OOOO^=oO@O@O@OOOooOO^\O@@@@OoOOOOOOoOOO@@@@@@@OO@@@`.=OOOOOOooOo/^o*,/OOOOOOOOOO\..*.. ./OOO]     ,.].  
//...*****\@@@@@@@O`,OOOOOoo\@OO][[OO@@@o@O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOo^=OOooo@OOO@O@@ooOO^*\O`****...........................o/**O`*=OOO@@OOO/oo/O^**\O@@OO@OOOOOoOOO@@@@@@@@@@@^..OOOOOOOooO\O*]OO/`oOOOOOOOOOO\` .***,oOOOOO\].     
//`*.*****.,O@@@@@Oo/,@@@@@\OOOO`/`,@O/ooOO@@OOOO@@@@@@@@@@@@@@@@@@@@@@@@@O@OOO`***\Oo*=@OOOOOOO\/oO^*******................................O*/o@OOOOOOO**.=O****\OOOOOOOOOoOOO@@@@@@@@@@@/ .OOOOOooooOo/^OOOOOO`\,OOOOOOO/.,OO\*****[OOOOOOOOOo]
//**`***......\@@/***=O@@@@@@@@Oooo]..\O@@O]/\OOOO@@@@O@OO@@@@@@@@@@@@@@@@@@O/\**.   ...=`.....`,/\]*.**.***............................... . .*,`.....`...O/..../OOOOOOOOoOOO@@@@@@@@@@@@  /OOOOoooooO\^,OOOOOOOO],,\OO/. /OOOOOO]`***,\OOOOOOOO
//\.*^*******..o*,]o/[[[O@@@@Oooooooo\`.\OOO@@@O]/oOOOOO@@@@@@@@@@@@@@@@@@@O@O^*,]...Oo,........,=O^.....*...................................o*..........*=^.....OOOOOOOOoOOO@@@@@@@@@@@@`.=O@@Ooooo/O^o./OOOOOOOOOO\**....OOOOOOOOOO\`***,oOOOOO
//\OOo`..***]o/[...**....*\OO/ooooOOOooO\.[OOOOOO@@OO\ooOO@@@@OO@@@@@@@@@@@@@Oo^...\o.,[`.......=O`........................................   ...........o`.   .*OOOOOOO\OOO@@@@@@@@@@@@^..O@@Ooo\//OOo.=OOOOOOOOOoO/.... ,`.[OOOOOOOOOOO\`**,o/[
//O],@@[*.. .............**/`..,[[^`,`***\\.\oooooOO@@@@@@\,\OOOOOO@@@@@@@@@O@O/\. ..,\`,[O\]]oO`..........................................    .,]`...]/`      .=OOOOO\OOOO@@@@@@@@@@@@@O`OO@@o[*`,OO/.,OOOOOOOooo^. .... **,OO].[OOOOOO[[. .,]]*
//O]\^.           ..........=^*]**`......**[\.      .,=O^,[\O@O],[OO@@OO@@@@@O@/\,]`   ,*\]..................................................                .*==OOOOoOOOOO@@@@@OO@@@@@@OOO@@/,**,OO\`.o\OOOOOOO^..`......OO\,*,O[  .,]OOOOOOoOoo
//OOOO]....             ........**`****..]OOOo`     .**/^*******[O@\..[\OOO@OO\O]`..,[o]]]\,@\``.  ..................................................  ..]/\`**/OOO\OOOOOO@@@@@@@@@@@@@OOO@@OOO],OO\` `.\ooOOO/.=O^ .... =O[`  ]`*\OOOOOOOOOOOOOo
//@@OOOOO]..,,.              ...**...,OOOOOOOOO^   .\**=OO^*******\OO`    .[OOO^\`*..........*[@O^\]... .....................  ............................,**/OO\OOOOOOO@@@@@@@@@@@@@OOO@@OOOOOOO\`   . .[o/.,oO/ ..... .]/OOOOOOOo\oOO@OOOOOOOo
//@@@@@@OOOO`..,\]`             **\o/[[o\][OOOOO\. .\]*,[`........*\oo^        .[O]*.............,O`[=\o]... ..................]...........................=OO/,O[O\OOOOOOO@@@@@@@@@OOOO@@OOOOOOO\^.     .  .OOOO .... =OOOOOOOOOOOOOOOO@OOOOOOoo
//@@@@@@@@@OOOO]`...[].   ...]o^**^oooo]oo]`,[ooOO`.OOO^******......,o/`            .[]`............\O..**[[o]`... ............,\`.,.....................*/O[O[***=^\OOOOOOO@@@@@@Oo\OO@@@@OOOOOo/.        ...,`.... ,OOOOOOOOOOOOOOOOOO@OOOOOOoo
//@@@@@@@@@@@@OOOOOOO]`.,*.  ,o^**o*ooooOOOOOoOo\]O` [\`..********.. .**]                .,\]..........\\`.*...*[oo]]..  .........\....................,/\/. =]**=\O\\OOOOO/=@@@@O/,OO@@@@OOOOOO/`          . . ..  \/ooOOOOOOOOOOOOOOOO@OOOOoOoo
//@@@@@@@@@@@@OOOOOOOOOOOO[`,``.**^**/oOOOOOOOOOOOoo*.[`...****.=OOOOOOOOO`                  ..,[\`........[,.[oOO]`..,[      .........       ......,/O`....`/O^/OOOOOO[,/OOoo@@O`=O@@@@@O@@OOOo`             . ..]     [\OOOOOOOOOOOOOO@OOOOoooo
//@@OOOOOOOOOOOOOOOOO[.         ..`,`..,]`...`.]..,....,\`.*****=]`.[OOOOOOO`            ..        ..,[]......,\`*[[\[`...../OOO]. .....       .]/[. .=.....=O\OO[[]/OO/Oooooo\/./O@@@@@@@O[[\/                 ,*.,`        ,\OOOOOOOOOOOoOOoooo
//OOOOOOOOOOOOO/[               ...          ./^...*/`oOOo******,[OOOOO]..[OOO               ....    .*,\*.,*,.,.[OOO\.oo[[.,]].]]]]/\]].[`..        ./^ ,]oOO=OOOOOO@O@O/[ooo\[/[@@@@@O[.....,\                .\`..\`           ,[OOOOOOooooo/[
//OOOOOOO[[                     ..         ]O[,*,/`       .*****=oO]` ,[OOOOO]],\].                   ..,`*.`.....,\OO\]..*,OO\*=OOO\]/OO\O\]]`.     .O\^ .\O`=`.,[OOO\O@@@O],[o\[`o]^**,.......,`              ...\...\`               .[\OOooo]
///[.                                   ]Ooo[/[.          .******  \OOoOO]`.[\OOOOOOOo`,..............  ................[\\..*,``=OOO@@OOO/[..    .]]]`\O\. *  .......`,[\OOO[[....... . *........\             ...  \...\`                   ./`
//                                   /OOOO[.              .******    =O`   OO@@]/\O/[[****..................... .......  ....[\[[[/OOOOO[[[[[\.    .[[./OOO..............   ..\/\`...    .\^.......=`           .*.    \`..\\               ,/,* 
//                              .]OO/[.                   .******          O*..=..,[]`,o\],.............,.......    .    .......,.O.`..,\O`*`**Oo]. ..oo\/.\`,.\......        ..  ,[].    .^.  ..../.           .*.      []*.,\.         ./[/..  
//                          ..[.                          ,]]]]]*          O*..=.       .[ooOO@@@@OOoo\].OO......   ...  ........,O`.......[O]]OOOOOOO\/O]]]`*...,oo\         ..    ./     =.    .,^            .*.       .,\]*.\`   .]O/`....*  
//                                                        =ooooo^          O*..O            ...,[\/OO@@@@@@@@`*/\]....... .......**\\.......***,O@@OOOOO\`\/`..[,O^/`*/.      =.    .^.     \   . /             .*.       .     ..,`. ......**.  
//                                                        =OOOOO^         =/..=`               ...  ..[[OOOO@@O`\OOOOOo\].....*******[\`.,/\\OOOo[\[[\\oooo]]]]/]]]OO=^       ^    .,./`    =.   =O`            .*.                 .....***...  
//                                                        =OOO/`.         /`..^                   ...........[[O\],[[oOOoOO\........***,O`,O/[]`*,/[`[OOOOOooOOOOOOOOO.      ..    .o`  ,` ,/   =. [^           ...                ....***.....  
//                                                        =Oo`..         .^..^                       =/]............[\O\`..........***....\\....      .\O`**...,O][`*=.      .    .=o.    \o.   /*/]=\`         ..                 ..***....  .  
//                                                        =/..           o.,.           ............**O\oOO]..............[\\]/\O@@O\]]]]]..,\.      ..***\....=^*****      ..    ,O=.     ,`  //`,*..              .]      .      .**....  ...  
//                                                        ..  ...       /.`  .]`,[........*********,/oO^[oOOOOO\`...............\OOOOO@@@@@@OO@@\.    **....\`.=\O\..*.     .    .O^=^.      ,Oo/\o\....       ,]@/[` \@O.....     ...... ....*  
//                                                       ..,]]]]`      oO[[......,***********,]ooooooooO**OOOOOOOOOO].......]OOOOOOOOOOOO\/\O@@@OOOO]. .......,Oo/\Ooo]]  ..     //**\^       .\Ooooo`.   ,]OO`***[OO` \O\....     ..........*=  
//                                               ,]oo\[[**=OOOOOo....//.*.***********]]oooooooooooooOOOOO**OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOOOOO\o\OOOOOO]......O.,\/oOo\/\/.    =O]OOOO^.     ...OOOo^..     ..          ...*..     .......***=  
//                                           ]Oo`*********OOOOOo`********,/oooooooooooooooooooooOOOOOOOOOO*oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooOO\][OOOO]..=O\. ,\`*o\`.*..,O,OOOOOO\`.  .....=O/...      .oOO/[o[`]].***..     .....*****=  
//                                        /Oo`************OOOo`**********oooooooooooooooooOOOOOOOOOOOOOOOOO/OOOOOOOOOOO]OOOOOOOOOO@O][\OOOOOOOOOOoo^****,\O\]\[O]..`.  ,\]*[\OO[**,^.\OOOOOO].....=O..]]*...    ,O@OoO/\O^*`*``.   ...********=  
//                                     ./o/***************OO[*************,ooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOoOOOOOOOOOOOO/.....,@@@[,OOOOOOOOOOOO/*....       .[O]/\].    .\]******\^.OoOOooOo/..=OOOOo].,[\o[[[`.........*...,\`...***********  
//                                    /oo`***********************************[\ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO[.    .O`,/OOOOOOOOOOOOO^...            .***[oOO].   .[\```*,OOOooo`/.../OOOOOOoo*.,`.]..[[]]`*.******.....***********=  
//                                  .//O*,****************************,oo`******,OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\]]]/OOOOOOOOOOOOOOO@O^.              .^*,]/],`*[oo]`. .`..,oooo/`.../OOOOOOOOO`...    ...[*].,[oo\]`*...***********=\]
//                                 .*,oo******************************=OOO^*********[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@O/=O`.               oooooooo***......`].,Ooo/....OOOOOOOOOOOO`..    .... ......*`]*,[o^**********\\]
//                                 **oo^^\o]`*]`**********************,=OOo*************[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO/....o/..              =ooooo`*.............=\O\...OOOOOOOOOOoo*...    ..   ........    ..******]]oo/^\
//                                ..,oooooooooooo^`*******************``=OO*******,oo]*****,\OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@Oo[.......oo*.              =ooo`*....     ......./`...OOOOOOOOOOoo`*..     .. .. . ..**.     .**********=OO
//                                .*=oooooooooooooo^********************,\O^*^*****,oooooo`***`*,[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@Oo[..... .    =o\*.             =***....        ......\...OOOOOO`,[OOo^*...             .***.     .***********  
//                               .**=oO=oooooooooooo`*********************O\/=********\ooOOOoo]`******/[\O@@@OOOOOOOOOOOOOO@OOo[.....        ...oo`.            .`......       ...........OOOOOOOOO\o\`.[\`...           .***.     .***********  
//                               ...=oOoooooooooooooo*********************\@o\ooooooooooooooOOOOOoo\`[`]/o\ooo]]/[O@@O@@OO/[.....    ............==*.           ........................=OOOOOOOOOOooOoOOO\].,...        .***.     .***********  
//                                ..=oOooooooooooooooo********************`O@O\o\ooooooooooooooOOOOOOOOOOo\o/o/\/OOOoo/`..............................         ......................./OOOOOOOOOOOOoo*,\oOOo*`,[\\.      .***.     .**********=  
//                               ...,oOoooooooooooooooo`******************^\=@Oooooooooooooooo/oooOOOOOOOOO@@OOoo/[...................................       ....................]/OOOOOOOO\OOOOOOOo/**..,\O\,*`*=`.     .***.     .**********=  
//                               ...*=oOoooooooooooooooo********************=oOOOoooooooooooooooooooOO@OOooo/[......................................     ...................]/OOOOOOOOOOOO`=OOOOOOOo^*......\O*OOOO     ..***.     .**********=  
//                                .*.*oOooooooooooooooooo`******************=o/=OOoooooooooOOOOOOOOoO/[......................................         .....           ,]OOO/\OOOOOOOOOOOO^,OOOOOOOoo**...    .,O^,=`   ...***.     .**********=  
//                                ...*=oOoooooooooooooooo*********``***`]//OOO@OOOOOOOOOoooo/[[[........................................                        .]/OOOOOO[ =OOOOOOoOOOOO^.OOOOOOOo/^*....       .\/@   ..**...     .**********=  
//                                  *.*oOOooooooooooooooo*********`,oOOOO[[`.........................................................                       ,/OOOOOOOOO` ,OOOOOOOooOOOO^ /OOOOOOoo**....           \^  .**..,@OO.. .**********=  
//                                 ....=oOOoooooooooooo\**[\/`/\oOO/`..........................................................                          ]OOOOOOOOOO/..,OOOOOOOOOoOOOO/ =OOOOOOoo`*....                .**..  ...  .***********  
//                                  ...*=oOooooooooooooo[[*\*]O/*..........................................................                          ]OOOOOOOOOOOO\^./OOOOOOOOOOOOOOO/ .OOOOOOoo^*....                 .**.        .**********=  
//                    ..             ...*\OOoooooooo^*[*],\OO`..........................................................                         ,/OOOOOOOOOOOO/.,`/OOOOOOOOOOOOOoOOO..=OOOOOoo^**....                 .**.        .**********=  
//                                    ...*\OOoo/\`o`**`,oOO^*.......................................................                          ]OOOOOOOOOOOOOOO^ ./OOOOOOOOOOOOOOOoOO...=OOOOooo**....                  .**..       .**********=  
//                       .             ...*ooOO\o^***,oOOo*....................................................                           ,/OOOOOOOOOOOOOOOOO^./OOOOOOOOOOOOOOOOOoo....OOOOooo**....                   .....       .**********=  
//                            .         ...*[oOO\****oOo`*...................................................                          ,OOOOOOOOOOOOOOOOOOOO,OOOOOOOOOOOOOOOOOOOOo..*..OOOooo**.....                   .....       .**********=  
//                            ..         ....,oOoo*******.....................................   .......                           .]OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.....=OOooo^*.....                    .....       .**********=  
//                                .        ...*=oo\*****................................... ............                        ./OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`.....=oooo^*.....                     .....       .**********=  
//                               ..         ....*oo^***.................................  .*...... ...                       ,/OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`......=oo^**.....                      .**..       ..*********=  
//                                           .....,o^**..............................  .,`........  .                    .,/OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`.... ..=oo**......                      =\`..        ...**ooo\*=. 
//                                            ......***............................  ./`........... ...               .,/OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`....  ..o^**......            .... .     =oo..        ....*,oooo=..
//                                             ......***........................     *.............                ../OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`....   .*=^*.......      ............    ......       ....**,****,..

